### ISSUE TITLE
Make CSS generic and move to root folder

### ISSUE THREAD

**Issue by tyrann0us** [mizansyed/wdImageStax#1]
Currently, `example/css/wdImageStax.css` expects the image stack to have `id` of `gallery-holder`. This is bad because most people probably choose different `id`s or `class`es for the stack. You should add a `class` (not `id`!) with JS and apply styles using this `class`.

Furthermore you should move the CSS file out of the `example` folder into the root.

Thanks.

**Comment by mizansyed** [comment]
You can have any id or class you want. I am sure what you mean otherwise. Should I change the example to classes?

**Comment by tyrann0us** [comment]
Please take a look at the CSS file I mentioned above.
It starts with `#gallery-holder {…}`. As I tried to explain this would require all image stacks to have exactly this `id`, otherwise the CSS wouldn't get applied.

You should completely rewrite the CSS file, remove the fixed `width` and `height` properties and the global `img` selector.

Thanks!

**Comment by mizansyed** [comment]
This is just an example. I have updated the stylesheet.

**Comment by tyrann0us** [comment]
Great!
I think what you should do is to add an even more generic CSS file to the root folder of your plugin. Because in the `readme.md` you explicitly reference this file:

```
Optional: Add wdImageStax.css:
<link href="css/wdImageStax.css" rel="stylesheet">
```

Thanks!
